FROM ubuntu:14.04

MAINTAINER FSSlc, liuchang011235 AT gmail DOT com

# install essential packages
RUN \
mkdir -p /root/Pkg && \
# use aliyun's mirror for better download speed
sed -i 's/archive.ubuntu.com/mirrors.aliyun.com/g' /etc/apt/sources.list && \
apt-get update && \
apt-get install -y make automake autoconf wget build-essential libboost-dev \
mpi-default-dev mpi-default-bin openmpi-bin libtbb-dev nano # libhypre-dev trilinos-all-dev petsc-dev libdeal.ii-dev --no-install-recommends

## set some env varibles
COPY env.txt /root/Pkg/env.txt 
COPY deal.II-6.3.1-updated.tar.gz /root/Pkg/deal.II-6.3.1-updated.tar.gz

## prepare deal.II AFEPack easymesh 
RUN \
## compile dealii v6.3.1
tar -xzf /root/Pkg/deal.II-6.3.1-updated.tar.gz -C /root/Pkg && \
cd /root/Pkg/deal.II && ./configure && make baseo laco -j9 && \
rm -rf ./lib/lac/* && \
rm -rf ./lib/base/* && \
rm -rf ./lib/contrib/* && \
rm -rf ./contrib && \
rm -rf ./examples && \
rm -rf ./doc && \
## link dealii include directory and lib
cd /usr/local/include && \
ln -s /root/Pkg/deal.II/deal.II/include . && \
ln -s /root/Pkg/deal.II/lac/include/lac . && \
ln -s /root/Pkg/deal.II/base/include/base . && \
cd /usr/local/lib && \
ln -s /root/Pkg/deal.II/lib/lib* . && \
## prepare for AFEPack easymesh
cd /root/Pkg && \
wget http://dsec.pku.edu.cn/~rli/AFEPack-snapshot.tar.gz && \
wget http://dsec.pku.edu.cn/~rli/source_code/easymesh.c.gz && \
tar -xzf ./AFEPack-snapshot.tar.gz -C /root/Pkg/  && \
gunzip easymesh.c.gz && \
## compile and install AFEPack
cat /root/Pkg/env.txt >> /root/.bashrc && . /root/.bashrc && \
cd /root/Pkg/AFEPack && \
sed -i "s/-std=c++14/-std=c++11/g" configure.ac && \
aclocal && autoconf && automake --add-missing && \
env EXTRA_INCDIR="-I/root/Pkg/deal.II/base/include -I/root/Pkg/deal.II/lac/include" EXTRA_LIBDIR="-L/root/Pkg/deal.II/lib -L /usr/lib/x86_64-linux-gnu/" ./configure && \
# make -j8 && make install
cd ./template/ && make -j8 && cd ../library/ && make -j8 && make install && \
cd ../example/ && make -j8 && \
## compile and install easymesh
cd /root/Pkg/ && \
gcc -o easymesh easymesh.c -lm && \
mv ./easymesh /usr/local/bin/ && \
## do some clean work
rm easymesh.c AFEPack-snapshot.tar.gz env.txt deal.II-6.3.1-updated.tar.gz && \
rm -rf /var/lib/apt/lists/*

CMD ["/bin/bash"]